### ISSUE TITLE
게시판 관련 기능- 게시글 등록

### ISSUE THREAD

**Issue by YunoJeon** [ProjectGoGym/BackEnd#10]
### 💼 작업 설명

알림 API 관련 기능입니다.
API 명세서 - 5. POST API Statement
ERD ([Link](https://www.erdcloud.com/d/vCntp4nvTKi9ycvgG)): Notification Table 기반으로 구현

### ✅ To-do

- [ ] todo 1 : 게시글 구현
- 사용자가 게시글을 생성 하는것을 구현
- [ ] todo 2 : 헬스장 구현
- 개시글을 등록할때 헬스장을 입력받아 저장
- [ ] todo 3 : 지역 받아오기 api 구현
- 사용자가 상위 지역을 선택하면 하위 지역을 보내주는 api 구현
