### ISSUE TITLE
FE 요청으로 구독 시 이벤트 발송 지연

### ISSUE THREAD

**Issue by YunoJeon** [ProjectGoGym/BackEnd#103]
### 💼 작업 설명

- sse 최초 구독 후 첫 이벤트 발송을 2초 지연
- sse 테스트가 진행 됨에 따라 발생한 예외 처리 필요
### ✅ To-do

- [ ] Thread 를 2초 정도 지연시켜 이벤트 발송을 늦춥니다.
- [ ] 타임아웃 시 예외처리를 추가합니다
- [ ] Runtime Exception 발생 시 content type 이 text event stream 으로 발생되게끔 추가합니다
