### ISSUE TITLE
채팅방 생성 시 초기 메시지 브로드캐스팅을 위한 Event 발행

### ISSUE THREAD

**Issue by Rud2K** [ProjectGoGym/BackEnd#122]
### 💼 작업 설명
채팅방 생성 시 채팅 요청자가 채팅을 요청하였다는 메시지를 브로드캐스팅 해주기 위해 Event를 발행

### ✅ To-do
- [ ] todo 1 : `ApplicationEvent`를 상속받은 이벤트 클래스 정의
- [ ] todo 2 : 채팅방 생성 시 이벤트 발행
- [ ] todo 3 : 채팅방 생성 이벤트를 Listener할 EventListener 클래스 정의
