### ISSUE TITLE
멤버(회원) 관련 기능

### ISSUE THREAD

**Issue by BaekSeungHyun7** [ProjectGoGym/BackEnd#2]
---
name: 멤버(회원) 관련 기능
about: 멤버(회원) 관련 기능
title: 멤버(회원) 관련 기능
labels: 
assignees: ''

---

### 💼 작업 설명
멤버(회원) 관련 기능 입니다.
API 명세서 - 1. Member API Statement (Member API)
ERD (https://www.erdcloud.com/d/vCntp4nvTKi9ycvgG) : Member Table 을 기반으로 구현했습니다.
 

### ✅ To-do

- [ ] todo 1 : 사용자 계정 및 인증 관리

회원가입 / 로그인 / 로그아웃 / 비밀번호 재설정 / 이메일 검증 / 이메일 인증 코드 확인 / 이메일 중복 확인 / 닉네임 중복 확인

- [ ] todo 2 : 프로필 및 활동 관리

내 정보 조회(마이페이지) / 내 정보 수정 / 회원탈퇴 / 내가 작성한 게시글 / 내가 찜한 게시글 / 최근 본 게시글

- [ ] todo 3 : 거래 및 회원 탐색

특정 회원 조회 / 구매 목록 조회 / 판매 목록 조회

**Comment by BaekSeungHyun7** [comment]
설정 안된 부분은 작업 중간에 설정해두겠습니다.
