### ISSUE TITLE
게시글 관련 기능

### ISSUE THREAD

**Issue by Rud2K** [ProjectGoGym/BackEnd#3]
### 💼 작업 설명
게시글 API 구현
API 명세서 - 5. Post API Statement (Post API)
ERD [Link](https://www.erdcloud.com/d/vCntp4nvTKi9ycvgG): Post Table을 기반으로 구현

### ✅ To-do
- [ ] todo 1 : 게시글 등록 및 수정
  - [ ] 게시물 등록 (POST /api/posts)
    - 게시글 제목, 내용, 가격, 회원권 만료일 및 남은 횟수, 위치 정보, 이미지를 전달받아 저장
    - 이미지 업로드 기능 연동 (AWS S3)
  - [ ] 게시글 수정 (PUT /api/posts/{post-id})
    - 게시글 소유자 확인 후 삭제 가능
    - post_status가 '거래 대기' 중인 경우에만 게시물 수정 가능
    - 헬스장 정보는 변경 불가능
- [ ] todo 2 : 게시글 조회
  - [ ] 게시글 목록 조회 (GET /api/posts?page={page}&size={size})
    - 필터(지역, 카테고리 등) 및 페이징 기능 구현
    - 찜 수, 등록일자, 생성된 채팅 수 정렬 옵션 제공
  - [ ] 게시글 상세 조회 (GET /api/posts{post-id})
    - 특정 게시글의 상세 정보 제공
- [ ] todo 3 : 부가 기능
  - [ ] 게시글 찜하기/찜해제 (POST /api/posts/{post-id}/wish)
    - 게시글에 찜 상태를 토글하는 기능
