### ISSUE TITLE
알림 관련 기능

### ISSUE THREAD

**Issue by YunoJeon** [ProjectGoGym/BackEnd#5]
### 💼 작업 설명

알림 API 관련 기능입니다.
API 명세서 - 7. NOTIFICATION API Statement
ERD ([Link](https://www.erdcloud.com/d/vCntp4nvTKi9ycvgG)): Notification Table 기반으로 구현

### ✅ To-do

- [ ] todo 1 : SSE 구독 설정
- 사용자가 로그인 시 SSE 를 연결하고 유지
- [ ] todo 2 : 알림 생성 시 알림 반환
- 사용자의 알림 목록 api 구현
- [ ] todo 3 : 알림 읽음 처리
- 사용자가 알림을 확인하면, 읽음처리 후, 반환값 정리
