### ISSUE TITLE
WebSocket 연결 시 JWT 인증 기능

### ISSUE THREAD

**Issue by Rud2K** [ProjectGoGym/BackEnd#62]
### 💼 작업 설명
WebSocket 초기 연결 시 JWT 인증 로직 구현
- WebSocket 연결 요청 시 STOMP 메시지를 통한 통신 중 초기 연결 단계에서 JWT를 사용하여 사용자 인증을 진행
- 인증된 사용자 정보는 STOMP 세션에 저장되어 이후 메시지 송수신 시 활용
- 클라이언트가 WebSocket 연결 요청 엔드포인트로 요청을 보낼 때, JWT의 유효성을 검증하고 인증된 사용자 정보를 WebSocket STOMP 세션에 저장하도록 구현

### ✅ To-do

- [x] todo 1 : JWT 인증 로직
  - WebSocket 연결 요청 시 Authorization 헤더에서 JWT를 추출하고 검증하는 로직 구현
- [x] todo 2 : STOMP 세션 정보 설정
  - 인증 성공 시 STOMP 세션에 사용자 정보를 저장
- [x] todo 3 : WebSocket 필터 제외 처리
  - `JwtAuthenticationFilter`에서 WebSocket 연결 요청(`/ws`)에 대한 필터 제외 설정
- [x] todo 4 : WebSocket 엔드포인트 설정
  - `WebSocketConfig`에서 `/ws` 엔드포인트 및 Origin 허용 설정
- [x] todo 5 : STOMP 메시지 인증 처리
  - 메시지 브로커에서 STOMP 세션 정보를 활용하여 인증된 사용자만 메시지를 송수신 할 수 있도록 처리
